services:
  mysql:
    container_name: mysql-place
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USERNAME: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY: 1
    ports:
      - '3306:3306'
    networks:
      - project3
    volumes:
      - data-mysql:/var/lib/mysql
  rabbitmq:
    container_name: rabbitmq-place
    image: 'rabbitmq:4.0.2'
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    ports:
      - '5672:5672'
    networks:
      - project3
networks:
  project3:
    driver: bridge
volumes:
  data-mysql:
    driver: local

